spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 9200
  servlet:
    context-path: /screen
#  ssl:
#    key-store: classpath:tomcat.pkcs12
#    key-password: 123456
#    key-store-type: PKCS12
socketio:
  port: 9201